# Generated by Django 6.0.5 on 2026-06-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
