# Generated by Django 6.0.5 on 2026-06-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0005_alter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
