# Generated by Django 6.0.5 on 2026-06-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userss', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
